### ISSUE TITLE
[RFC] OpenSergo universal transport service with gRPC

### ISSUE THREAD

**Issue by sczyh30** [opensergo/opensergo-proto#1]
The gRPC transport protocol between the OpenSergo Control Plane and SDKs is fundamental for implementation. Now we'd like to propose a customized gRPC service, the OpenSergo universal transport service (OUTS), as the underlying transport layer.

(TBD...)

---

OpenSergo 控制平面与 SDK 之间的 gRPC 传输协议及机制设计至关重要。为此，社区提出一种基础而又通用的设计 - *OpenSergo universal transport service (OUTS)*，作为传输协议。

**Comment by xzd1621** [comment]
1. 订阅配置的正常流程

![image](https://user-images.githubusercontent.com/30654585/187684049-00897ec1-1a3c-4223-b62e-d91eb0201dfe.png)

在订阅配置时，指定namespace、name、app和kind等参数，Control plane给SDK返回CRD，SDK接收到之后再给Control Plane响应。设计成类似三次握手的原因就是需要确保SDK可以收到Control Plane推给它的CRD。 

2. 配置有误
如果SDK接收到CRD之后认为CRD有问题，可以在NACK响应中返回给Control Plane错误信息细节。
![image](https://user-images.githubusercontent.com/30654585/187684367-41c734ec-2095-4baf-81cb-9d67f5352a19.png)

3.  版本管理
给配置设置版本号，用来区分配置的新旧，如果由于网络原因新配置比旧配置先到，那么SDK收到之后就会抛弃旧的配置而不处理。
![image](https://user-images.githubusercontent.com/30654585/187684467-d1d33164-7f41-4506-a449-72b066113e90.png)

**Comment by yunwz** [comment]
> 

这一实现类似Istio的MCP(over xDS)协议,但是怎么解决配置增量更新的问题呢?

**Comment by sczyh30** [comment]
OpenSergo universal transport service 目前的订阅机制是带范围的订阅 (namespace, app, kind)，推送时不会推送整个集群全量的数据；然后针对某个订阅组，它的变更推送是全量的，但这个量级不会很大、频率也不会很频繁。

社区也在设计针对某个订阅组的增量推送机制，这一块也欢迎大家一起讨论。
